"""
umn_subjects.py
---------------
Static list of all UMN Twin Cities undergraduate subject codes.
Sourced from the Schedule Builder subjects page (Fall 2026).

This list changes rarely — new subjects are added maybe once a year.
Update by visiting: schedulebuilder.umn.edu/explore/courses?campus=UMNTC&term=1269
"""

UMN_SUBJECTS = [
    ("AHS", "Academic Health Center Shared"),
    ("ACCT", "Accounting"),
    ("ADDS", "Addiction Studies"),
    ("ADPY", "Adult Psychology"),
    ("AEM", "Aerospace Engineering and Mechanics"),
    ("AIR", "Aerospace Studies"),
    ("AFRO", "African American and African Studies"),
    ("AECM", "Agricultural Education, Communication & Marketing"),
    ("AGRO", "Agronomy and Plant Genetics"),
    ("AMIN", "American Indian Studies"),
    ("ASL", "American Sign Language"),
    ("AMST", "American Studies"),
    ("ANAT", "Anatomy"),
    ("ANTH", "Anthropology"),
    ("APEC", "Applied Economics"),
    ("ARCH", "Architecture"),
    ("ART", "Art"),
    ("ARTH", "Art History"),
    ("ARTS", "Arts, Sciences and Engineering (Arden Hills)"),
    ("ARTB", "Arts and Sciences"),
    ("ASTR", "Astronomy"),
    ("BIOL", "Biology"),
    ("BIOT", "Biotechnology"),
    ("BME", "Biomedical Engineering"),
    ("BCHE", "Biochemistry"),
    ("BCBT", "Biochemistry/Biophysics/Medical Genetics"),
    ("BIOC", "Biochemistry (Medical School)"),
    ("BIOM", "Biomedical Informatics"),
    ("BIOP", "Biophysics"),
    ("BUS", "Business"),
    ("BUSN", "Business Administration"),
    ("BLAW", "Business Law"),
    ("CBST", "CBS Topics"),
    ("CI", "Curriculum and Instruction"),
    ("CHEM", "Chemistry"),
    ("CHIN", "Chinese"),
    ("CINE", "Cinema and Media Arts"),
    ("CLA", "Classical Languages"),
    ("CLAS", "Classical Languages and Literature"),
    ("CLON", "Clinical Laboratory Science Online"),
    ("COGS", "Cognitive Science"),
    ("COMM", "Communication Studies"),
    ("CSCI", "Computer Science"),
    ("CF", "Consumer Food Science"),
    ("COUN", "Counseling and Student Personnel Psychology"),
    ("CSCL", "Cultural Studies and Comparative Literature"),
    ("DNCE", "Dance"),
    ("DST", "Disability Studies"),
    ("DISC", "Disciplinary"),
    ("ECON", "Economics"),
    ("EDUC", "Education"),
    ("EEB", "Ecology, Evolution, and Behavior"),
    ("EE", "Electrical Engineering"),
    ("ESCI", "Earth Sciences"),
    ("ENGL", "English"),
    ("ENGR", "Engineering"),
    ("ESST", "Environment and Society"),
    ("ENVE", "Environmental Engineering"),
    ("ENVS", "Environmental Sciences, Policy and Management"),
    ("EPSY", "Educational Psychology"),
    ("ESL", "English as a Second Language"),
    ("ETHN", "Ethnic Studies"),
    ("FMCH", "Family, Community and Mental Health"),
    ("FSOS", "Family Social Science"),
    ("FINN", "Finance"),
    ("FINC", "Financial Management"),
    ("FOOD", "Food Science and Nutrition"),
    ("FOR", "Forest Resources"),
    ("FREN", "French"),
    ("GERM", "German"),
    ("GLBL", "Global Studies"),
    ("GREK", "Greek"),
    ("GEOG", "Geography"),
    ("GEOL", "Geology"),
    ("HDFS", "Human Development and Family Science"),
    ("HEBR", "Hebrew"),
    ("HIST", "History"),
    ("HMNG", "Hmong"),
    ("HMED", "History of Medicine"),
    ("HMS", "Health and Medical Sciences"),
    ("HSEM", "Honors Seminar"),
    ("HORT", "Horticulture"),
    ("HWMN", "Humanities"),
    ("IBUS", "International Business"),
    ("IDSc", "Industrial and Systems Engineering"),
    ("IE", "Industrial and Systems Engineering"),
    ("IDSC", "Information Decision Sciences"),
    ("INFO", "Information"),
    ("INDE", "Independent Study"),
    ("JOUR", "Journalism"),
    ("JAPA", "Japanese"),
    ("JWST", "Jewish Studies"),
    ("KNES", "Kinesiology"),
    ("KOR", "Korean"),
    ("LAAS", "Latin American and Caribbean Studies"),
    ("LAT", "Latin"),
    ("LLAW", "Law"),
    ("LING", "Linguistics"),
    ("MGMT", "Management"),
    ("MKTG", "Marketing"),
    ("MATH", "Mathematics"),
    ("MATS", "Materials Science"),
    ("ME", "Mechanical Engineering"),
    ("MEBT", "Medical Biochemistry"),
    ("MICB", "Microbiology"),
    ("MILI", "Military Science"),
    ("MSCI", "Military Science"),
    ("MUSC", "Music"),
    ("NURS", "Nursing"),
    ("NTRN", "Nutrition"),
    ("NSCI", "Neuroscience"),
    ("OMS", "Operations Management"),
    ("PATH", "Pathology"),
    ("PHSL", "Physiology"),
    ("PHAR", "Pharmacy"),
    ("PHIL", "Philosophy"),
    ("PA", "Physical Activity"),
    ("PE", "Physical Education"),
    ("PHYS", "Physics"),
    ("PLPA", "Plant Pathology"),
    ("PLSC", "Plant Science"),
    ("POL", "Political Science"),
    ("PORT", "Portuguese"),
    ("PREV", "Preventive Medicine"),
    ("PRNT", "Print and Digital Media"),
    ("PROD", "Production and Operations Management"),
    ("PSTL", "Postsecondary Teaching and Learning"),
    ("PSY", "Psychology"),
    ("PUBH", "Public Health"),
    ("PUBL", "Publishing"),
    ("REAL", "Real Estate"),
    ("RHET", "Rhetoric"),
    ("RUSS", "Russian"),
    ("SCAN", "Scandinavian Studies"),
    ("SCO", "Supply Chain and Operations"),
    ("SOC", "Sociology"),
    ("SOIL", "Soil"),
    ("SPAN", "Spanish"),
    ("SPED", "Special Education"),
    ("STAT", "Statistics"),
    ("SUST", "Sustainability"),
    ("SWED", "Swedish"),
    ("SWRK", "Social Work"),
    ("THET", "Theatre"),
    ("TURK", "Turkish"),
    ("UROP", "Undergraduate Research"),
    ("URBS", "Urban Studies"),
    ("VBS", "Veterinary Biosciences"),
    ("VMED", "Veterinary Medicine"),
    ("WGSS", "Women, Gender, and Sexuality Studies"),
    ("WRIT", "Writing Studies"),
    ("YIDD", "Yiddish"),
]